FROM node:18
# Create app directory
WORKDIR /usr/src/service1
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

#RUN mkdir -p /usr/src/logs && touch /usr/src/logs/service1.log

RUN touch /usr/src/logs/service1.log

COPY package*.json ./
RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev
# Bundle app source
COPY . .
EXPOSE 3000
CMD [ "node", "service1.js" ]