version: '3'
services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"  
    volumes:
      - ./service1:/usr/src/service1  
      - nodejs-logs:/usr/src/logs  
    depends_on:
      - service2  # Ensure that the Python app service starts first
    networks:
      mycustomnetwork:
        ipv4_address: 172.20.0.1

  service2:
    build:
      context: ./service2  
      dockerfile: Dockerfile  
    ports:
      - "8000:8000" 
    volumes:
      - ./service2:/usr/src/service2  
      - python-logs:/usr/src/logs
    networks:
      mycustomnetwork:
        ipv4_address: 172.20.0.2

networks:
  mycustomnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  nodejs-logs:  
  python-logs:  